services:
  - type: web
    name: resume-analyzer-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false # Render will prompt you to enter this value
      - key: JWT_SECRET
        sync: false # Render will prompt you to enter this value
      - key: GEMINI_API_KEY
        sync: false # Render will prompt you to enter this value
